-- Dados pessoais e de saúde não devem ser acessíveis pela chave publicável.
-- A aplicação acessa essas tabelas exclusivamente no servidor via Prisma.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Student" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HealthHistoryVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lifestyle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BodyCompositionProtocol" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BodyAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Exercise" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExerciseAlias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Periodization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingWeek" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingDay" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlannedExercise" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkoutSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PerformedExercise" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
